name: Build, Push & Deploy to Kubernetes
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: lindenes/configurations
          token: ${{ secrets.ACCESS_TOKEN }}
          path: configuration

      - name: checkout config file
        run: |
          mv configuration/samurai-face-app/config.yaml .env.local

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            lindenes/face-app:latest

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure Kubernetes
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

          kubectl cluster-info
          kubectl get nodes

      - name: Rollout Restart Deployment
        run: |
          kubectl rollout restart deployment/face-app -n prod
